services:
  - type: static_site
    name: birthday-wish
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
