services:
  - type: web
    name: birthday-wish
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
